version: "3"

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodb
            MONGO_INITDB_ROOT_PASSWORD: ee6Caiche3ti9ko

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
            ME_CONFIG_MONGODB_ADMINPASSWORD: ee6Caiche3ti9ko
            ME_CONFIG_MONGODB_URL: mongodb://mongodb:ee6Caiche3ti9ko@mongo:27017/
